package ru.debajo.reader.rss.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF656100)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFefe84e)
val md_theme_light_onPrimaryContainer = Color(0xFF1e1c00)
val md_theme_light_secondary = Color(0xFF626042)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe8e4bf)
val md_theme_light_onSecondaryContainer = Color(0xFF1d1c05)
val md_theme_light_tertiary = Color(0xFF3f6655)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc0ecd6)
val md_theme_light_onTertiaryContainer = Color(0xFF002115)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffcf3)
val md_theme_light_onBackground = Color(0xFF1c1c16)
val md_theme_light_surface = Color(0xFFfffcf3)
val md_theme_light_onSurface = Color(0xFF1c1c16)
val md_theme_light_surfaceVariant = Color(0xFFe7e3d1)
val md_theme_light_onSurfaceVariant = Color(0xFF48473a)
val md_theme_light_outline = Color(0xFF797768)
val md_theme_light_inverseOnSurface = Color(0xFFf4f0e7)
val md_theme_light_inverseSurface = Color(0xFF31302b)

val md_theme_dark_primary = Color(0xFFd1cb31)
val md_theme_dark_onPrimary = Color(0xFF353200)
val md_theme_dark_primaryContainer = Color(0xFF4c4800)
val md_theme_dark_onPrimaryContainer = Color(0xFFefe84e)
val md_theme_dark_secondary = Color(0xFFccc8a4)
val md_theme_dark_onSecondary = Color(0xFF333118)
val md_theme_dark_secondaryContainer = Color(0xFF4a482c)
val md_theme_dark_onSecondaryContainer = Color(0xFFe8e4bf)
val md_theme_dark_tertiary = Color(0xFFa5d0bb)
val md_theme_dark_onTertiary = Color(0xFF0c3728)
val md_theme_dark_tertiaryContainer = Color(0xFF274e3e)
val md_theme_dark_onTertiaryContainer = Color(0xFFc0ecd6)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1c1c16)
val md_theme_dark_onBackground = Color(0xFFe6e2d9)
val md_theme_dark_surface = Color(0xFF1c1c16)
val md_theme_dark_onSurface = Color(0xFFe6e2d9)
val md_theme_dark_surfaceVariant = Color(0xFF48473a)
val md_theme_dark_onSurfaceVariant = Color(0xFFcac7b5)
val md_theme_dark_outline = Color(0xFF949181)
val md_theme_dark_inverseOnSurface = Color(0xFF1c1c16)
val md_theme_dark_inverseSurface = Color(0xFFe6e2d9)

val seed = Color(0xFFb7b110)
val error = Color(0xFFba1b1b)